title: Cyberdeck
hero_image: images/banner.png
description: Build your own cyberdeck with a Raspberry Pi.
listed: false
pdf: false
build: true
steps:
  - title: What you will make
  - title: Choose a Raspberry Pi
  - title: Match the power supply
  - title: Choose input devices
  - title: Choose a display
  - title: Install Raspberry Pi OS
    completion:
      - engaged
  - title: Switch on your Raspberry Pi
  - title: On the desktop
  - title: Use Raspberry Pi Connect
  - title: Connect with SSH
  - title: Build an enclosure
    completion:
      - internal
  - title: Sideband
  - title: Knitdeck
  - title: Toolbox terminal
  - title: Challenge
    challenge: true
    completion:
      - external
