title: Cyberdeck
hero_image: images/banner.png
description: Build your own cyberdeck with a Raspberry Pi.
listed: false
pdf: false
build: true
steps:
  - title: What you will make
  - title: Choose a Raspberry Pi
  - title: Plugging in
  - title: Install Raspberry Pi OS
    completion:
      - engaged
  - title: Choose a keyboard
  - title: Choose a display
  - title: Set up your Raspberry Pi
  - title: Use Raspberry Pi Connect
  - title: Connect with SSH
  - title: Add a button
  - title: Add lights
  - title: Build an enclosure
    completion:
      - internal
  - title: Challenge
    challenge: true
    completion:
      - external
